version: '1.1'
services:
  mongodb:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_blog:/data/db

  backend:
    image: prakashmishr/blog-backend 
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - "5002:5002"
    environment:
      MONGODB_URL: "mongodb://mongoDB:27017"
      JWTSECRET: "mySecreat"

  frontend:
      image: prakashmishr/blog-frontend 
      container_name: frontend
      depends_on:
        - backend
      ports:
        - "3000:3000"
      environment:
        REACT_APP_SERVER_URL: "http://localhost:5002"

volumes:
  mongodb_data_blog:


