services:
  - name: blog-frontend
    type: web
    env: docker
    image: prakashmishr/blog-frontend:latest
    envVars:
      - key: REACT_APP_SERVER_URL
        value: https://backend-service-url
    ports:
      - port: 3000

  - name: blog-backend
    type: web
    env: docker
    image: prakashmishr/blog-backend:latest
    envVars:
      - key: JWTSECRET
        value: mySecret
    autoDeploy: true
    ports:
      - port: 5002

