services:
  - name: blog-frontend
    type: web
    env: docker  # Specifies that it's a Docker-based environment
    image: prakashmishr/blog-frontend:latest  # Docker image for the frontend
    envVars:
      - key: REACT_APP_SERVER_URL
        value: https://backend-service-url  # Replace with actual backend Render service URL
    ports:
      - port: 3000  # Specifies the port to expose the service

  - name: blog-backend
    type: web
    env: docker
    image: prakashmishr/blog-backend:latest  # Docker image for the backend
    envVars:
      - key: MONGODB_URL
        value: mongodb+srv://prakashmishr:XPGaJLpoQDRh24ns@cluster0.drbse.mongodb.net/holidayhub?retryWrites=true&w=majority
      - key: JWTSECRET
        value: mySecret
    autoDeploy: true  # Automatically deploy on changes
    ports:
      - port: 5002  # Specifies the port to expose the service

